language: node_js
node_js: stable
git:
  submodules: true
cache:
  directories:
  - node_modules #cache models to speed up the build
install:
  - npm install -g hexo-cli
  - npm install -g firebase-tools
  - npm install hexo --save
script:
 - hexo clean && hexo generate --debug
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
