language: node_js
node_js: stable
cache:
  directories:
  - node_modules #cache models to speed up the build
install:
  - npm install -g hexo-cli
  - npm install -g firebase-tools
  - npm install hexo --save
script:
- hexo generate
after_success:
  - firebase deploy --project memoblog-19b5a --token $FIREBASE_TOKEN
