language: node_js
node_js: stable
git:
  submodules: true
cache:
  directories:
  - node_modules
before_install:
  - npm install -g hexo-cli
  - npm install -g firebase-tools
  - npm install hexo --save
install:
  - npm install
script:
 - hexo clean && hexo generate -d
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
